name: Deploy Discord Bot - Production
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          port: ${{ secrets.SSH_PORT_PROD }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /app/discordbot
            git fetch origin main
            git merge -s recursive -X theirs origin/main
            npm install
            pm2 stop all
            pm2 start main.js