name: Deploy Discord Bot - Development Build
on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          port: ${{ secrets.SSH_PORT_DEV }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir /app/discordbot-dev 2>/dev/null
            cd /app
            git clone --branch dev https://github.com/desaerun/discordhistorybot.git discordbot-dev 2>/dev/null
            cd /app/discordbot-dev
            git fetch origin dev
            git merge -s recursive -X theirs origin/dev
            npm install
            pm2 stop all 2>/dev/null
            pm2 start main.js