name: Deploy Discord Bot - Production Build
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          port: ${{ secrets.SSH_PORT_PROD }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir /opt/prod-discordbot 2>/dev/null
            cd /opt
            git clone --branch mail github-desaerun:desaerun/discordhistorybot.git prod-discordbot 2>/dev/null
            cd prod-discordbot
            git stash
            git fetch origin main
            git merge -s recursive -X theirs origin/main
            npm install
            pm2 stop all 2>/dev/null
            pm2 start main.js